### PR TITLE
Replace restler

### LINKED ISSUE #25: restler dependency imports qs library, which has a security vulnerability
Is there a safer way to manage query parameters than by using `restler`?

https://app.snyk.io/test/npm/wdio-reportportal-reporter/0.0.21?tab=dependencies

### PR DESCRIPTION
**Pull request by BorisOsipov**
Replace abandoned rest client `resler` with `axios`

Fix #25

### CODE REVIEW

**Comment by BorisOsipov** [comment]
Trigger CI

**Comment by BorisOsipov** [comment]
Trigger CI

**Comment by BorisOsipov** [comment]
@thephilwells can you help with reviewing this?

@AlehVasilyeu Thanks for sharing your work on this 🙏

**Comment by thephilwells** [comment]
Yep, I'll take a look

**Review by chuma-forever — APPROVED** [review]
No comments, looks good

**Comment by BorisOsipov** [comment]
@DzmitryHumianiuk would you mind merging this?

**Review by DzmitryHumianiuk — APPROVED** [review]

**Comment by DzmitryHumianiuk** [comment]
@BorisOsipov done

**Pull request merged**
