### PR TITLE
Use dynamic page size in launch merge

### LINKED ISSUE #86: Merge launches does not include more than 20 launches
I started to use the new RP 5 versions of "client-javascript" and "agent-js-cypress" and noticed that if there are more than 20 launches to be merged only the first 20 are included in the merged launch. Remaining are left as is. The problem seems to be that the ReportPortal API returns by default only 20 launches, thus, cropping the rest out.

We are using the manual merging option in "agent-js-cypres", but not sure if that really matters.

This could be fixed at https://github.com/reportportal/client-javascript/blob/master/lib/report-portal-client.js#L280 by adding the  `page.size` parameter to the search parameters like this:

```
            const params = new URLSearchParams({
                'filter.in.uuid': launchUUIds,
                'page.size': launchUUIds.length,
            });
```

Not able to create the pull request myself as I already have forked the repo and cannot delete the fork currently. For us this is a blocker issue and not able to use the new versions before this is fixed.

### PR DESCRIPTION
**Pull request by JanisDzalbe**
Fix issue when only first 20 launches are merged

### CODE REVIEW

**Comment by JanisDzalbe** [comment]
This is intended to fix https://github.com/reportportal/client-javascript/issues/86
Code change taken from the issue description

**Comment by ajaythumma** [comment]
can someone please review this?

**Comment by ajaythumma** [comment]
Hello, checking to see if anyone able to review this?

**Comment by gustawx** [comment]
@thomaswinkler, What happens with the fix? already 1 year passed and this is a painful issue

**Comment by gustawx** [comment]
@AmsterGet current fix will not really fix the issue. There will be a problem with larger test sets. There need to be a function to iterate through pages to collect the results.

For e.g. I have almost 2000 tests, I'm pretty sure that's too much for a single request.

**Review by AmsterGet — APPROVED** [review]

**Comment by AmsterGet** [comment]
Let's merge it to bypass limitation. Thank you @JanisDzalbe !

> There need to be a function to iterate through pages to collect the results.

Thank you @gustawx! I suppose we will consider such approach as an option later.

**Pull request merged**
