### PR TITLE
Fix an issue with headers

### PR DESCRIPTION
**Pull request by ranazya**
Object.assign was assigning the incorrect headers which resulted in an error while trying to add attachments.

### CODE REVIEW

**Comment by AmsterGet** [comment]
Hi @Ranazya !
Could you describe the issue in detail?

**Comment by ranazya** [comment]
Hey @AmsterGet,

Yes after the update the attachment steps started breaking when we have different types of attachments, for example: first we attach log as text and then attach a screenshot, the log would be sent correctly but the headers for the screenshot won't.

We'd get the following error after attempting to add the second attachment:
`Error: Request failed with status code 415: {"timestamp":1597562848816,"status":415,"error":"Unsupported Media Type","message":"Content type 'multipart/form-data;boundary=9869808852;charset=UTF-8' not supported","path":"/v1/{project}/item/{id}"} `

**Comment by AmsterGet** [comment]
@Ranazya 
Thanks for the explanation
The spread operator has been changed to `Object.assign` due to support for Node.js version 8. [here](https://github.com/reportportal/client-javascript/commit/47b68fcd63bbd942159c8010ea55f2d5510a851d).
As far as I understand, the problem is related to the fact that now `Object.assign` copies properties to `this.header` instead of creating a new object.
Therefore, I suggest using `Object.assign` with the first parameter of an empty object to fix the bug and keep Node.js 8.x support.
```
{
                headers: Object.assign({}, this.headers, {
                    'Content-Type': `multipart/form-data; boundary=${MULTIPART_BOUNDARY}`,
                }),
},
```
What do you think?

**Comment by ranazya** [comment]
@AmsterGet Yes, that would fix the issue!
I've reverted my changes and added the empty object.

Thanks!

**Review by AmsterGet — APPROVED** [review]

**Pull request merged**
